version: "3.3"
services:
  web:
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    links:
      - php
    command: [nginx-debug, '-g', 'daemon off;']
  php:
    build: ./docker-php
    volumes:
      - ./:/app
    links:
      - database
  database:
    image: "mysql:5.7.33"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=touchyourpass
      - MYSQL_USER=olivier
      - MYSQL_PASSWORD=gnu_coding_cafe
